name: orcvio-cov
channels:
  - pytorch=1.10
  - conda-forge
  - anaconda
  - nvidia
  - defaults
dependencies:
  - click
  - cudatoolkit
  - ffmpeg
  - filterpy
  - g2o
  - gstreamer
  - hdf5
  - libopencv
  - matplotlib
  - mkl
  - numpy
  - opencv
  - pandas
  - pillow
  - pip
  - py-opencv
  - pyglet
  - pyopengl
  - pyparsing
  - pyqt
  - pytest
  - python
  - python-dateutil
  - python_abi
  - pytorch
  - pytz
  - qt
  - readline
  - scipy
  - setuptools
  - six
  - sqlite
  - tk
  - toml
  - tomli
  - tornado
  - transforms3d
  - typing_extensions
  - unicodedata2
  - wheel
  - x264
  - xz
  - zipp
  - zlib
  - zstd
  - pip:
    - pybind11
    - sophuspy
